local:
  hosts:
    192.168.215.135:
      domain: test.grafikart.fr
      root_path: "/home/{{ ansible_user }}/test.grafikart.fr"
      self_signed: yes
      database: grafikart
      database_password: dotted-statue-hurt
      typesense_key: P8SSmEw4gvSe3gdQXyyQW87FYr4AKRf5Sxk5nrXGyGk
      ansible_user: debian
remote:
  hosts:
    grafikart:
      ansible_user: grafikart
      domain: grafikart.fr
      root_path: "/home/{{ ansible_user }}/grafikart.fr"
      plausible_path: "/home/{{ ansible_user }}/stats.grafikart.fr"
      self_signed: no
      database: grafikart
      ansible_python_interpreter: /usr/bin/python3
      docker: false
      php_version: 8.2
