resources:
  App\Domain\Forum\Entity\Report:
    shortName: 'forum/report'
    operations:
      ApiPlatform\Metadata\Post:
        security: is_granted("forumReport")
        denormalizationContext:
          groups: [ 'create:report' ]
          swagger_definition_name: 'ReportCreate'
        normalizationContext:
          groups: [ 'read:report' ]
          swagger_definition_name: 'ReportRead'
        openapi_context:
          summary: Crée un nouveau signalement
      ApiPlatform\Metadata\Delete:
        security: is_granted("DELETE_FORUM_REPORT", object)

  App\Domain\Forum\Entity\Topic:
    shortName: 'forum/topic'
    collectionOperations: [ ]
    operations:
      ApiPlatform\Metadata\Get:
        normalizationContext:
          groups: [ 'read:topic' ]
      ApiPlatform\Metadata\Delete:
        security: is_granted("DELETE_TOPIC", object)

  App\Domain\Forum\Entity\Message:
    shortName: 'forum/message'
    collectionOperations: [ ]
    operations:
      ApiPlatform\Metadata\Get:
        normalizationContext:
          groups: [ 'read:message' ]
      ApiPlatform\Metadata\Delete:
        security: is_granted("DELETE_FORUM_MESSAGE", object)
      ApiPlatform\Metadata\Put:
        denormalizationContext:
          groups: [ 'update:message' ]
        normalizationContext:
          groups: [ 'read:message' ]
        security: is_granted("UPDATE_FORUM_MESSAGE", object)

  App\Domain\Notification\Entity\Notification:
    operations:
      ApiPlatform\Metadata\GetCollection:
        security: is_granted("ROLE_USER")
        pagination_client_items_per_page: true
        normalizationContext:
          groups: [ 'read:notification' ]
      ApiPlatform\Metadata\Post:
        security: is_granted("CREATE_NOTIFICATION")
        normalizationContext:
          groups: [ 'read:notification' ]
        denormalizationContext:
          groups: [ 'create:notification' ]
